### ISSUE TITLE
Not working, can you share the exact details on how to export alerts

### ISSUE THREAD

**Issue by ukreddy-erwin** [youngpabl0/grafanaalertsexporter#2]
Not working, can you share the exact details on how to export alerts
The example is not useful.

**Comment by youngpabl0** [comment]
wazzup, please provide more diagnostic information, did u specify all options of script? what in your console while executing it?
thanx

**Comment by ukreddy-erwin** [comment]
I tried on minikube and eks based cluster.

With Ubuntu shell configured with kubectl.

The configuration file values I provided but not working.

It would be better you share a working example for minikube or eks.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by youngpabl0** [comment]
it doesnt matter where is exaclty your grafana instance, if u specify all options correctly - script will work
i ask you about diagnostic information - u dont provide it, i close issue, thank u
